version: '3.6'

services:

  front:
    image: bernardo1234/frontend
    container_name: frontend
    hostname: fronend
    environment:
      TZ: America/Guayaquil
    ports:
    - 4200:4200
    networks:
      - datalogger_net
    depends_on:
      - srvwildfly

  srvdb:
    image: postgres
    container_name: srvdb
    hostname: srvdb
    environment:
      POSTGRES_USER: consultas
      POSTGRES_DB: consultas
      POSTGRES_PASSWORD: QueryConSql.pwd
      TZ:  America/Guayaquil
    ports:
      - 5432:5432
    networks:
      - datalogger_net
    volumes:
      - pg_data2:/var/lib/postgresql/data

  srvwildfly:
    image: bernardo1234/demoappdocker
    container_name: srvwildfly
    hostname: srvwildfly
    environment:
      TZ:  America/Guayaquil
    ports:
      - 8082:8080
      - 8899:8009
      - 9992:9990
      - 8787:8787
    command: /opt/jboss/wildfly/bin/standalone.sh -b 0.0.0.0 -c standalone.xml -bmanagement 0.0.0.0 --debug *:8787
    depends_on:
      - srvdb
    networks:
      - datalogger_net

  admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: info@jasoft.ec
      PGADMIN_DEFAULT_PASSWORD: clave
      TZ:  America/Guayaquil
    ports:
      - 5050:80
    depends_on:
      - srvdb
    networks:
      - datalogger_net

  swaggereditor:
    depends_on:
      - srvwildfly
    image: swaggerapi/swagger-editor
    ports:
      - 9999:8080
    networks:
      - datalogger_net

  swaggerui:
    depends_on:
      - srvwildfly
    image: swaggerapi/swagger-ui
    ports:
      - 8888:8080

  jaegertracingio:
    depends_on:
      - srvwildfly
    image: jaegertracing/all-in-one:1.16.0
    ports:
      - 6831:6831/udp
      - 16686:16686
    networks:
      - datalogger_net

volumes:
  pg_data2:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: C:\Users\Bernardo Chuchuca T\Documents\DatosPostgres

networks:
  datalogger_net:
